---
- name: Set system_id_source = "uname"
  lineinfile:
    dest: '/etc/lvm/lvm.conf'
    regexp: '^\s*system_id_source'
    line: '       system_id_source = "uname"'
  notify:
    - rebuild initramfs

- name: get 'uname -n'
  command: uname -n
  register: lvm_uname
  changed_when: false
  check_mode: false

- name: get 'lvm systemid'
  command: lvm systemid
  register: lvm_systemid
  changed_when: false
  check_mode: false

- name: Check if uname and lvm systemid match
  fail:
    msg: "'{{ lvm_uname.stdout }}' (uname) does not match '{{ lvm_systemid.stdout.split(' ')[4] }}' (lvm systemid)"
  when: lvm_uname.stdout != lvm_systemid.stdout.split(' ')[4]
