---
- name: Enable locking_type=1
  lineinfile:
    dest: '/etc/lvm/lvm.conf'
    regexp: '^\s*locking_type'
    line: '        locking_type = 1'
  notify:
    - rebuild initramfs
    - rebuild initrd

- name: Include variables for rgmanager clusters on RHEL 5/6
  include_vars: rgmanager.yml
  when: (ansible_distribution_major_version == "6" and cluster_type == "rgmanager") or ansible_distribution_major_version == "5"

- name: Include variables for pacemaker clusters on RHEL 6
  include_vars: pacemaker.yml
  when: ansible_distribution_major_version == "6" and cluster_type == "pacemaker"
