---
## check if storage is where it should be
- name: Check existence of shared device
  stat: path={{ shared_drive }}
  register: shared_device_check
- fail: msg="Shared device doesn't exist on on node"
  when: shared_device_check.stat.exists != True

## setup HA-LVM tagging
- name: Setup HA-LVM tagging
  include: ha-lvm-tagging.yml
  when: HALVMtype == "tagging"

- name: Setup HA-LVM CLVM
  include: ha-lvm-clvm.yml
  when: HALVMtype == "clvm"
