---
# EL6, EL7
- hosts: cluster
  vars:
    # enable_repos: true      # RHEL-only
    # enable_eus_repos: false # RHEL-only
    local_vg_list:
      - 'vg_shared_c'
    clvm_vgs:
      - name: 'vg_shared_c'
        pvs: '/dev/sdb'
        lvs:
          - name: 'lv_name5'
            size: '200M'
  roles:
     - { role: 'ondrejhome.ha-cluster-lvm', HALVMtype: 'clvm' }
