---
- name: rebuild initramfs
  shell: "dracut -f"
  when: ansible_distribution_major_version >= "6"

- name: rebuild initrd
  shell: "mkinitrd -f /boot/initrd-$(uname -r).img $(uname -r)"
  when: ansible_distribution_major_version == "5"
